---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on ubuntu
    apt:
       name: apache2
       state: present
  
  - name: i want to copy file into webservers(ansiblenode)
    template:
      src: myindex.j2
      dest: /var/ww/html/index.html